apiVersion: apps/v1
kind: Deployment
metadata:
  name: partybridge-ui
  labels:
    app: partybridge-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: partybridge-ui
  template:
    metadata:
      labels:
        app: partybridge-ui
    spec:
      containers:
        - name: partybridge-ui
          image: jeffthenaef/pbui@sha256:0d867f485d07614c427dc8115ac3f5089bfa16fa94d1edd95af6a81db05dfd38
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: tls-certs
              mountPath: /app/cert
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: partybridge-io-tls

---
apiVersion: v1
kind: Service
metadata:
  name: partybridge-ui
spec:
  selector:
    app: partybridge-ui
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80

# ---

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: partybridge-ui-ingress
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     cert-manager.io/cluster-issuer: "letsencrypt"
# spec:
#   tls:
#   - hosts:
#       - testing.partybridge.io
#     secretName: partybridge-io-tls
#   rules:
#   - host: testing.partybridge.io
#     http:
#       paths:
#       - pathType: Prefix
#         path: "/"
#         backend:
#           service:
#             name: partybridge-ui
#             port:
#               number: 80
