apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: partybridge-io
  namespace: default
spec:
  secretName: partybridge-io-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - testing.partybridge.io
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer


---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: partybridge-io-wss
  namespace: default
spec:
  secretName: partybridge-io-tls-wss
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - wss.partybridge.io
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
