apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: partybridge-io
  namespace: default
spec:
  secretName: partybridge-io-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: www.partybridge.io
  dnsNames:
  - www.partybridge.io
  - partybridge.io

